### ISSUE TITLE
JSONB definition from ODOO

### ISSUE THREAD

**Issue by williamcastrillon** [article714/json_field#2]
Hi!
look here for an "official" definition of JSONB field type from ODOO

https://github.com/odoo/runbot/blob/13.0/runbot/fields.py

**Comment by Kontrolix** [comment]
Hi,

Thank you for contribution, i'm glad to see that our work has suggested some interest from somone else.

But that "official" definition of jsonb seems very strang to me. I don't see the point of using class FieldDict instead of just using a classic python Dict. It seems to add just more complexity for no real benefit? Could you clear this up to me?

Moreover, our implementation is more oriented toward json widget and guided edition. Our field definition is realy basic but it does exactly what we need, that is to say, serve json data to json widget and write it to database.

In addition, ORM side, we add possibility of using our json field in domain expression with postgresql's json operators and front side, json widget is able to validate content against a [json schema](https://json-schema.org/) .

Obviously, everything that I say know, is still in "beta" version. We just implement 2 types of postgresql's json operators in domain and for the guided style json widget, we don't implement all v7 json schema definition wet.

So, as far I know, surely our field definiton is simple and basic, but it do what it's need. But if you want to suggest some improvement that we could bring to it to improve it, you are welcom!
